### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by skateboard** [SirRina/B.O.P.E#2]
bruh what is this code???

**Comment by xcc8** [comment]
It's called java retard

**Comment by LucasBreeden** [comment]
it's called a war crime and im pretty sure those are illegal

**Comment by xcc8** [comment]
Are u insulting Rina you stupid piece of shit

**Comment by skateboard** [comment]
this is not proper java this looks like shit

**Comment by xcc8** [comment]
This java looks fine, Rina just has a different way if putting his folders. Stop being as fucking incel NN retard

**Comment by skateboard** [comment]
LOL the "java looks fine" so snake case is proper conventions out side of enums and constants? https://www.javatpoint.com/java-naming-conventions learn what you are talking about before you talk.

**Comment by skateboard** [comment]
like legit this whole client is in snake case and lining up things like bruh stop talking this repo is fucking horrible

**Comment by skateboard** [comment]
and yes bro he owns the domain just rina?? really fr dam can you have him tell me how he got a 1 word domain?

**Comment by cherosin** [comment]
rude

**Comment by HeroGlaucoP** [comment]
rude

**Comment by skateboard** [comment]
truth hurts

**Comment by HeroGlaucoP** [comment]
rina himself said the code was meh

**Comment by skateboard** [comment]
the code isnt meh its trash LOL

**Comment by HeroGlaucoP** [comment]
k boomer

**Comment by skateboard** [comment]
lmao at least ik when to call out idiots on there horrible attempt at java

**Comment by cherosin** [comment]
congrats

**Comment by skateboard** [comment]
thank you
